-- USERS TABLE
ALTER TABLE users
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;

-- ORDERS TABLE
ALTER TABLE orders
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;

-- CATEGORIES TABLE
ALTER TABLE categories
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;

-- PRODUCTS TABLE
ALTER TABLE products
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;

-- ORDER_ITEMS TABLE
ALTER TABLE order_items
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;