// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package db

import (
	"context"
)

const countListCategory = `-- name: CountListCategory :one
SELECT COUNT(*)
FROM categories
`

func (q *Queries) CountListCategory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListCategory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCategories = `-- name: CountSearchCategories :one
SELECT COUNT(*) 
FROM categories
WHERE name ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountSearchCategories(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchCategories, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, created_at, updated_at
FROM categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategory = `-- name: ListCategory :many
SELECT id, name, created_at, updated_at FROM categories
ORDER BY id
LIMIT $1 -- NUMBER OF ROWS TO RETURN
OFFSET $2 -- NUMBER OF ROWS TO SKIP
`

type ListCategoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategory(ctx context.Context, arg ListCategoryParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchCategory = `-- name: PatchCategory :one
UPDATE categories
SET name = COALESCE($2, name)
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type PatchCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) PatchCategory(ctx context.Context, arg PatchCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, patchCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeCategory = `-- name: RemoveCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) RemoveCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, removeCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchCategory = `-- name: SearchCategory :many
SELECT id, name, created_at, updated_at FROM categories
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY id
LIMIT $2 -- NUMBER OF ROWS TO RETURN
OFFSET $3 -- NUMBER OF ROWS TO SKIP
`

type SearchCategoryParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchCategory(ctx context.Context, arg SearchCategoryParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, searchCategory, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
